AllCops:
  TargetRubyVersion: 3.0
  NewCops: disable
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'log/**/*'
    - 'db/migrate/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

require:
  - rubocop-rails

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
